name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        required: true
        description: a branch name
jobs:
  environment-check:
    runs-on: ubuntu-latest
    env:
      BRANCH: "${{ inputs.branch }}"
    steps:
      - run: date
      - run: uname -a
      - run: ps -fe
      - run: apt list --installed
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - run: pwd
      - run: ls -la
